##set working directory and load libraries
setwd("C:/Users/Michel/Documents/R")

options(stringsAsFactors = FALSE)
library(data.table)

##load data
data<-read.table("C:/Users/Michel/Documents/R/household_power_consumption.txt",sep =";", header = TRUE)
data$Date <- as.Date( as.character(data$Date), format= "%d/%m/%Y")
dataGood<- subset (data, Date >= as.Date("2007-02-01")  & Date <= as.Date("2007-02-02"))
rm(data)

x<-as.numeric(dataGood$Global_active_power)
x2<-as.numeric(dataGood$Voltage)
x3<-as.numeric(dataGood$Sub_metering_1)
x4<-as.numeric(dataGood$Sub_metering_2)
x5<-as.numeric(dataGood$Sub_metering_3)
x6<-as.numeric(dataGood$Global_reactive_power)
a<-as.factor(weekdays(dataGood$Date))
legtext=c("Sub_metering_1","Sub_metering_2","Sub_metering_3")
par(mfrow=c(2,2))
plot(x,ylab="Global Active power",xaxt="n",type="l",ann=FALSE)
axis(1,at= 1:2880 ,labels=a)
plot(x2,ylab="Voltage",type="l",xaxt="n",ann=FALSE)
axis(1,at= 1:2880 ,labels=a)
#text(-2,-2,"datetime")
plot(x3,ylab="Energy Sub_meteringr",type="l",xaxt="n",ann=FALSE)
axis(1,at= 1:2880 ,labels=a)
lines(x4,type="l",col =2)
lines(x5,type="l",col =100)
legend("topright",legend = legtext)
plot(x6,ylab="Global_reactive_power",type="l",xaxt="n",ann=FALSE)
axis(1,at= 1:2880 ,labels=a)
dev.copy(png, file="Plot4.png", width = 480, height = 480)
dev.off()
#axis(1, dm$Date, format(dm$Date, "%b %d"), cex.axis = .7)